### ISSUE TITLE
Dataset does not download?

### ISSUE THREAD

**Issue by logan-markewich** [AIR-Bench/AIR-Bench#25]
Do I need to manually download the datasets?

```python
evaluation = AIRBench(
    benchmark_version="AIR-Bench_24.04",
    task_types=["long-doc"],      # remove this line if you want to evaluate on all tasks
    domains=["arxiv"],            # remove this line if you want to evaluate on all domains
    languages=["en"],             # remove this line if you want to evaluate on all languages
    # cache_dir="~/.air_bench/"     # path to the cache directory (**NEED ~52GB FOR FULL BENCHMARK**)
)
```

results in error

```
FileNotFoundError: Couldn't find a dataset script at /Users/loganmarkewich/giant_change/llama_index/AIR-Bench/long-doc_arxiv_en/long-doc_arxiv_en.py or any data file in the same directory. Couldn't find 'AIR-Bench/long-doc_arxiv_en' on the Hugging Face Hub either: FileNotFoundError: Unable to find 'hf://datasets/AIR-Bench/long-doc_arxiv_en@fa509c14d61d418fb0c046a131d5c987b71be809/AIR-Bench_24.04/gpt3/queries.jsonl' with any supported extension ['.csv',  .....]
```

**Comment by hanhainebula** [comment]
Hi! You don't need to manually download the dataset. Our script will automatically load the dataset from the huggingface. Can you provide the version of your `datasets` package?

**Comment by hanhainebula** [comment]
I just add a test here: https://github.com/AIR-Bench/AIR-Bench/blob/main/tests/load_data/test_load_data.py. 

You can try to see if it can run correctly.

**Comment by logan-markewich** [comment]
Thanks @hanhainebula  -- Here's the result after running that test

```bash
(venv) python ./test_download.py 
Downloading readme: 100%|██████████████████████████████████████████████████████████████████| 884/884 [00:00<00:00, 3.18MB/s]
Traceback (most recent call last):
  File "/Users/loganmarkewich/giant_change/llama_index/./test_download.py", line 29, in <module>
    test_load_data()
  File "/Users/loganmarkewich/giant_change/llama_index/./test_download.py", line 19, in test_load_data
    corpus, queries = data_loader.load_data(
  File "/Users/loganmarkewich/giant_change/llama_index/venv/lib/python3.10/site-packages/air_benchmark/evaluation_utils/data_loader.py", line 15, in load_data
    corpus_data = datasets.load_dataset(
  File "/Users/loganmarkewich/giant_change/llama_index/venv/lib/python3.10/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/Users/loganmarkewich/giant_change/llama_index/venv/lib/python3.10/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/Users/loganmarkewich/giant_change/llama_index/venv/lib/python3.10/site-packages/datasets/load.py", line 1875, in dataset_module_factory
    raise FileNotFoundError(
FileNotFoundError: Couldn't find a dataset script at /Users/loganmarkewich/giant_change/llama_index/AIR-Bench/long-doc_book_en/long-doc_book_en.py or any data file in the same directory. Couldn't find 'AIR-Bench/long-doc_book_en' on the Hugging Face Hub either: FileNotFoundError: Unable to find 'hf://datasets/AIR-Bench/long-doc_book_en@82be5b7af5d35e96e06f13f237318c305cafc426/AIR-Bench_24.04/origin-of-species_darwin/queries.jsonl' with any supported extension ['.csv', '.tsv', '.json', '.jsonl', '.parquet', '.geoparquet', '.gpq', '.arrow', '.txt', '.tar', '.blp', '.bmp', '.dib', '.bufr', '.cur', '.pcx', '.dcx', '.dds', '.ps', '.eps', '.fit', '.fits', '.fli', '.flc', '.ftc', '.ftu', '.gbr', '.gif', '.grib', '.h5', '.hdf', '.png', '.apng', '.jp2', '.j2k', '.jpc', '.jpf', '.jpx', '.j2c', '.icns', '.ico', '.im', '.iim', '.tif', '.tiff', '.jfif', '.jpe', '.jpg', '.jpeg', '.mpg', '.mpeg', '.msp', '.pcd', '.pxr', '.pbm', '.pgm', '.ppm', '.pnm', '.psd', '.bw', '.rgb', '.rgba', '.sgi', '.ras', '.tga', '.icb', '.vda', '.vst', '.webp', '.wmf', '.emf', '.xbm', '.xpm', '.BLP', '.BMP', '.DIB', '.BUFR', '.CUR', '.PCX', '.DCX', '.DDS', '.PS', '.EPS', '.FIT', '.FITS', '.FLI', '.FLC', '.FTC', '.FTU', '.GBR', '.GIF', '.GRIB', '.H5', '.HDF', '.PNG', '.APNG', '.JP2', '.J2K', '.JPC', '.JPF', '.JPX', '.J2C', '.ICNS', '.ICO', '.IM', '.IIM', '.TIF', '.TIFF', '.JFIF', '.JPE', '.JPG', '.JPEG', '.MPG', '.MPEG', '.MSP', '.PCD', '.PXR', '.PBM', '.PGM', '.PPM', '.PNM', '.PSD', '.BW', '.RGB', '.RGBA', '.SGI', '.RAS', '.TGA', '.ICB', '.VDA', '.VST', '.WEBP', '.WMF', '.EMF', '.XBM', '.XPM', '.aiff', '.au', '.avr', '.caf', '.flac', '.htk', '.svx', '.mat4', '.mat5', '.mpc2k', '.ogg', '.paf', '.pvf', '.raw', '.rf64', '.sd2', '.sds', '.ircam', '.voc', '.w64', '.wav', '.nist', '.wavex', '.wve', '.xi', '.mp3', '.opus', '.AIFF', '.AU', '.AVR', '.CAF', '.FLAC', '.HTK', '.SVX', '.MAT4', '.MAT5', '.MPC2K', '.OGG', '.PAF', '.PVF', '.RAW', '.RF64', '.SD2', '.SDS', '.IRCAM', '.VOC', '.W64', '.WAV', '.NIST', '.WAVEX', '.WVE', '.XI', '.MP3', '.OPUS', '.zip']
```

Running datasets==2.18.0

**Comment by logan-markewich** [comment]
After installing `datasets=2.19.1`, it seems to work. Thanks for the pointer and tests!

I would suggest updating the dependencies in the pip package for this 👍🏻

**Comment by hanhainebula** [comment]
> After installing `datasets=2.19.1`, it seems to work. Thanks for the pointer and tests!
> 
> I would suggest updating the dependencies in the pip package for this 👍🏻

This is strange🤔, because I can run the test correctly with `datasets==2.18.0` in my environment.

Anyway, thanks for your suggestion! We will consider to update the dependencies.
