### ISSUE TITLE
Not enough memory error when evaluating MS MARCO English

### ISSUE THREAD

**Issue by tomaarsen** [AIR-Bench/AIR-Bench#28]
Hello!

## Bug(?) report overview
* I experienced a "not enough memory" error when evaluating MS MARCO with English (task name: default)

## Details
Last night, I tried running the AIR Bench on [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) without a reranker. I ran it locally, where I can also run MTEB due to my RTX 3090 and 32GB of RAM. However, with AIR I received the following exception:

```
                                                                         Domain: msmarco
                                                                          Language: en                                                                           
                                                                       Task Name: default                                                                        
Downloading readme: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 458/458 [00:00<?, ?B/s]
Downloading data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 672k/672k [00:00<00:00, 1.76MB/s]
Downloading data: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 3.54G/3.54G [04:05<00:00, 14.4MB/s]
Generating queries_default split: 100%|██████████████████████████████████████████████████████████████████████████| 6319/6319 [00:00<00:00, 907540.30 examples/s]
Generating corpus_default split: 100%|████████████████████████████████████████████████████████████████████| 8872840/8872840 [00:05<00:00, 1549180.62 examples/s] 
Traceback (most recent call last):
  File "C:\code\AIR-Bench\scripts\sentence-transformers\evaluate_sentence_transformers.py", line 108, in <module>
    main()
  File "C:\code\AIR-Bench\scripts\sentence-transformers\evaluate_sentence_transformers.py", line 99, in main
    evaluation.run(
  File "C:\code\AIR-Bench\air_benchmark\air_benchmark.py", line 127, in run
    evaluator(
  File "C:\code\AIR-Bench\air_benchmark\evaluation_utils\evaluator.py", line 88, in __call__
    no_reranker_search_results = retriever(
  File "C:\code\AIR-Bench\scripts\sentence-transformers\utils\searcher.py", line 28, in __call__
    search_results = self.retriever(corpus=corpus, queries=queries)
  File "C:\Users\tom\.conda\envs\air_bench\lib\site-packages\mteb\evaluation\evaluators\RetrievalEvaluator.py", line 462, in __call__
    return self.retriever.search(
  File "C:\Users\tom\.conda\envs\air_bench\lib\site-packages\mteb\evaluation\evaluators\RetrievalEvaluator.py", line 141, in search
    cos_scores = self.score_functions[score_function](
  File "C:\Users\tom\.conda\envs\air_bench\lib\site-packages\mteb\evaluation\evaluators\utils.py", line 32, in cos_sim
    return torch.mm(a_norm, b_norm.transpose(0, 1))
RuntimeError: [enforce fail at alloc_cpu.cpp:114] data. DefaultCPUAllocator: not enough memory: you tried to allocate 224269903840 bytes.
```
The cosine similarity for the chunk was seemingly being done on CPU, and required 224269903840 bytes, aka 224 GB of memory. 

I ran my evaluation script like so:
```
python scripts/sentence-transformers/evaluate_sentence_transformers.py \
--task_types qa \
--languages en \
--output_dir ./search_results \
--encoder sentence-transformers/all-mpnet-base-v2 \
--search_top_k 1000 \
--batch_size 64 \
--normalize_embeddings True \
--overwrite False
```
It's possible that the hardcoded 10M corpus chunk size in `evaluate_sentence_transformers.py` is responsible here.

- Tom Aarsen

**Comment by hanhainebula** [comment]
Thank you for finding this problem! I just add a new parameter `corpus_chunk_size` to solve the problem. Now the default value is set to 50K, like in MTEB. You can try again now.

Looking forward to your feedback
